# Generated by Django 4.0.2 on 2022-03-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('Fname', models.CharField(max_length=20)),
                ('Mname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('Link_Image', models.SlugField(blank=True)),
                ('C_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('Pa_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('Fname', models.CharField(max_length=10)),
                ('Mname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('P_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('MobilePhone', models.IntegerField(default=0, unique=True)),
                ('Email', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=10)),
                ('Sex', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Election_date', models.DateTimeField(auto_now=True, verbose_name='Election_date')),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.candidates')),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.people')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='Pa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parties'),
        ),
    ]
