# Generated by Django 4.0.2 on 2022-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='Fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Mname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parties',
            name='Name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='people',
            name='Email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='Lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='Mname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
